name: DSA Tests

on: [push]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm Package Manager
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Execute Vitest Solutions
        run: pnpm test
